# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5cbf2e94db3cf19387bc745e7f4aacfc"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "QR Code Manager"

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_app_proxy,write_app_proxy"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[app_proxy]
url = "/proxy"
prefix = "apps"
subpath = "qr-code"

[[webhooks.subscriptions]]
uri = "/webhooks/customers-data-request"
compliance_topics = ["customers/data_request"]

[[webhooks.subscriptions]]
uri = "/webhooks/customers-redact"
compliance_topics = ["customers/redact"]

[[webhooks.subscriptions]]
uri = "/webhooks/shop-redact"
compliance_topics = ["shop/redact"]
